const API_BASE = (location.hostname === 'localhost' || location.hostname === '127.0.0.1') ? 'https://stockpulse-live-2026.netlify.app/.netlify/functions' : '/.netlify/functions';
const POPULAR_SYMBOLS = [{symbol:'AAPL',name:'Apple Inc.'},{symbol:'MSFT',name:'Microsoft Corp.'},{symbol:'GOOGL',name:'Alphabet Inc.'},{symbol:'AMZN',name:'Amazon.com Inc.'},{symbol:'TSLA',name:'Tesla Inc.'},{symbol:'META',name:'Meta Platforms'},{symbol:'NVDA',name:'NVIDIA Corp.'},{symbol:'NFLX',name:'Netflix Inc.'},{symbol:'AMD',name:'Advanced Micro Devices'},{symbol:'INTC',name:'Intel Corp.'},{symbol:'ORCL',name:'Oracle Corp.'},{symbol:'QCOM',name:'Qualcomm Inc.'},{symbol:'ADBE',name:'Adobe Inc.'},{symbol:'CRM',name:'Salesforce Inc.'},{symbol:'PANW',name:'Palo Alto Networks'},{symbol:'AVGO',name:'Broadcom Inc.'},{symbol:'PLTR',name:'Palantir Technologies'},{symbol:'CRWD',name:'CrowdStrike Holdings'},{symbol:'SNOW',name:'Snowflake Inc.'},{symbol:'NET',name:'Cloudflare Inc.'},{symbol:'DDOG',name:'Datadog Inc.'},{symbol:'MDB',name:'MongoDB Inc.'},{symbol:'V',name:'Visa Inc.'},{symbol:'MA',name:'Mastercard Inc.'},{symbol:'JPM',name:'JPMorgan Chase'},{symbol:'COIN',name:'Coinbase Global'},{symbol:'SQ',name:'Block Inc.'},{symbol:'PYPL',name:'PayPal Holdings'},{symbol:'GS',name:'Goldman Sachs'},{symbol:'BAC',name:'Bank of America'},{symbol:'UBER',name:'Uber Technologies'},{symbol:'SHOP',name:'Shopify Inc.'},{symbol:'ABNB',name:'Airbnb Inc.'},{symbol:'NKE',name:'Nike Inc.'},{symbol:'SBUX',name:'Starbucks Corp.'},{symbol:'LLY',name:'Eli Lilly'},{symbol:'UNH',name:'UnitedHealth Group'},{symbol:'ABBV',name:'AbbVie Inc.'},{symbol:'MRNA',name:'Moderna Inc.'},{symbol:'PFE',name:'Pfizer Inc.'},{symbol:'XOM',name:'Exxon Mobil'},{symbol:'CVX',name:'Chevron Corp.'},{symbol:'WMT',name:'Walmart Inc.'},{symbol:'KO',name:'Coca-Cola Co.'},{symbol:'PG',name:'Procter and Gamble'},{symbol:'COST',name:'Costco Wholesale'},{symbol:'HD',name:'Home Depot'},{symbol:'BA',name:'Boeing Co.'},{symbol:'CAT',name:'Caterpillar Inc.'},{symbol:'GE',name:'GE Aerospace'},{symbol:'TCS.NS',name:'Tata Consultancy Services'},{symbol:'INFY.NS',name:'Infosys Ltd.'},{symbol:'WIPRO.NS',name:'Wipro Ltd.'},{symbol:'HCLTECH.NS',name:'HCL Technologies'},{symbol:'HDFCBANK.NS',name:'HDFC Bank'},{symbol:'ICICIBANK.NS',name:'ICICI Bank'},{symbol:'SBIN.NS',name:'State Bank of India'},{symbol:'RELIANCE.NS',name:'Reliance Industries'},{symbol:'BAJFINANCE.NS',name:'Bajaj Finance'},{symbol:'LT.NS',name:'Larsen and Toubro'},{symbol:'MARUTI.NS',name:'Maruti Suzuki'},{symbol:'TATAMOTORS.NS',name:'Tata Motors'},{symbol:'SUNPHARMA.NS',name:'Sun Pharmaceutical'},{symbol:'BHARTIARTL.NS',name:'Bharti Airtel'},{symbol:'TATASTEEL.NS',name:'Tata Steel'},{symbol:'ZOMATO.NS',name:'Zomato Ltd.'},{symbol:'NTPC.NS',name:'NTPC Ltd.'}];
const DEFAULT_WATCHLIST = ['AAPL','MSFT','TSLA','NVDA','GOOGL','META','AMZN','NFLX'];
const WL_VERSION = '4';
if (localStorage.getItem('wl_version') !== WL_VERSION) { localStorage.setItem('watchlist', JSON.stringify(DEFAULT_WATCHLIST)); localStorage.setItem('wl_version', WL_VERSION); }
let watchlist = JSON.parse(localStorage.getItem('watchlist') || JSON.stringify(DEFAULT_WATCHLIST));
let stockData = {}, historyCache = {}, selectedSymbol = null, selectedRange = '1d', currentPage = 'dashboard';
const REFRESH_MS = 5000, HISTORY_TTL = 60000;
let refreshCountdown = 5, prevPrices = {};
function seededRand(seed){let s=seed>>>0;return function(){s+=0x6D2B79F5;let t=Math.imul(s^(s>>>15),1|s);t^=t+Math.imul(t^(t>>>7),61|t);return((t^(t>>>14))>>>0)/4294967296;};}
function strSeed(str){let h=0;for(let i=0;i<str.length;i++)h=Math.imul(31,h)+str.charCodeAt(i)|0;return Math.abs(h);}
const BASE_PRICES={AAPL:192,MSFT:415,TSLA:175,NVDA:875,GOOGL:175,AMZN:185,META:505,NFLX:635,AMD:165,INTC:30,JPM:198,BAC:38,V:275,MA:465,WMT:68,KO:62,PEP:175,MCD:295,SBUX:78,NKE:92,PLTR:25,CRWD:320,SNOW:155,NET:95,DDOG:115,MDB:245,COIN:225,SQ:72,PYPL:62,XOM:115,CVX:155,BA:185,CAT:345,GE:165};
function getMockHistory(symbol,range){const seed=strSeed(symbol+range+Math.floor(Date.now()/3600000));const rand=seededRand(seed);const base=BASE_PRICES[symbol]||(strSeed(symbol)%400+20);const counts={'1d':78,'5d':65,'1mo':22,'3mo':65,'10y':120};const n=counts[range]||30;const data=[];let price=base*(0.94+rand()*0.12);const now=new Date();for(let i=0;i<n;i++){const open=parseFloat(price.toFixed(2));const close=parseFloat(Math.max(open+(rand()-0.48)*price*0.014,0.01).toFixed(2));const high=parseFloat((Math.max(open,close)*(1+rand()*0.007)).toFixed(2));const low=parseFloat((Math.min(open,close)*(1-rand()*0.007)).toFixed(2));const volume=Math.floor(rand()*5e6+1e6);let label;if(range==='1d'){const mins=Math.floor((i/n)*390);const h=Math.floor(9+(30+mins)/60);const m=(30+mins)%60;label=h+':'+m.toString().padStart(2,'0');}else if(range==='10y'){const d=new Date(now);d.setMonth(d.getMonth()-(n-i));label=d.toLocaleDateString([],{month:'short',year:'2-digit'});}else{const d=new Date(now);d.setDate(d.getDate()-(n-i)*(range==='3mo'?3:1));label=d.toLocaleDateString([],{month:'short',day:'numeric'});}data.push({date:label,open,high,low,close,volume});price=close;}return data;}
function getMockQuote(symbol){const history=getMockHistory(symbol,'1d');const last=history[history.length-1],first=history[0];const price=last.close,prevClose=first.open;const change=parseFloat((price-prevClose).toFixed(2));const changePct=parseFloat(((change/prevClose)*100).toFixed(2));return{symbol,name:POPULAR_SYMBOLS.find(s=>s.symbol===symbol)?.name||symbol,price,prevClose,change,changePct,volume:last.volume*15,dayHigh:Math.max(...history.map(d=>d.high)),dayLow:Math.min(...history.map(d=>d.low)),isMock:true};}
async function fetchQuote(symbol){try{const res=await fetch(API_BASE+'/quote?symbols='+encodeURIComponent(symbol),{signal:AbortSignal.timeout(8000)});if(!res.ok)throw new Error('bad');const data=await res.json();const q=data[symbol];if(!q||q.error)throw new Error('no data');return{...q,isMock:false};}catch{return getMockQuote(symbol);}}
async function fetchHistory(symbol,range){const key=symbol+'_'+range;const cached=historyCache[key];if(cached&&(Date.now()-cached.ts)<HISTORY_TTL)return cached.data;try{const res=await fetch(API_BASE+'/history?symbol='+encodeURIComponent(symbol)+'&range='+range,{signal:AbortSignal.timeout(10000)});if(!res.ok)throw new Error('bad');const json=await res.json();if(json.error||!json.rows?.length)throw new Error('empty');historyCache[key]={data:json.rows,ts:Date.now()};return json.rows;}catch{const mock=getMockHistory(symbol,range);historyCache[key]={data:mock,ts:Date.now()};return mock;}}
function toast(msg,type='info',duration=4000){const container=document.getElementById('toastContainer');const el=document.createElement('div');el.className='toast '+type;const icons={success:'✅',error:'❌',warning:'⚠️',info:'ℹ️'};el.innerHTML='<span>'+(icons[type]||'')+'</span><span>'+msg+'</span>';container.appendChild(el);setTimeout(()=>{el.classList.add('removing');setTimeout(()=>el.remove(),300);},duration);}
function navigateTo(page){currentPage=page;document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.page===page));document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id==='page-'+page));if(page==='portfolio')InvestmentIdeas.openPanel();if(page==='forecast')populateForecastSelect();}
function saveWatchlist(){localStorage.setItem('watchlist',JSON.stringify(watchlist));}
function addSymbol(symbol){symbol=symbol.trim().toUpperCase().replace(/[^A-Z0-9.\-]/g,'');if(!symbol)return;if(watchlist.includes(symbol)){toast(symbol+' already in watchlist','warning');return;}if(watchlist.length>=50){toast('Watchlist limit reached','error');return;}watchlist.push(symbol);saveWatchlist();renderSidebarWatchlist();renderDashboardCards();renderWatchlistGrid();AlertManager.updateSymbolSelect(watchlist);fetchAndUpdateSymbol(symbol);toast(symbol+' added','success');}
function removeSymbol(symbol){watchlist=watchlist.filter(s=>s!==symbol);delete stockData[symbol];Object.keys(historyCache).filter(k=>k.startsWith(symbol+'_')).forEach(k=>delete historyCache[k]);saveWatchlist();if(selectedSymbol===symbol){selectedSymbol=null;ChartManager.destroy();document.getElementById('chartPlaceholder').classList.remove('hidden');document.getElementById('chartTitle').textContent='Select a stock';document.getElementById('chartSubtitle').textContent='';}renderSidebarWatchlist();renderDashboardCards();renderWatchlistGrid();AlertManager.updateSymbolSelect(watchlist);toast(symbol+' removed','info');}
function renderSidebarWatchlist(){const container=document.getElementById('sidebarWatchlist');if(!container)return;container.innerHTML=watchlist.map(symbol=>{const d=stockData[symbol];const cls=d?(d.changePct>=0?'up':'down'):'';const chg=d?(d.changePct>=0?'+':'')+d.changePct.toFixed(2)+'%':'—';const isIN=symbol.endsWith('.NS');const displayPrice=d?(isIN?'₹':'$')+d.price.toFixed(2):'—';const displaySym=symbol.replace('.NS','').replace('.BO','');return '<div class="sidebar-stock-item '+(selectedSymbol===symbol?'active':''+'"')+' data-symbol="'+symbol+'"><div class="sidebar-stock-left"><span class="sidebar-stock-sym">'+displaySym+'</span><span class="sidebar-stock-price">'+displayPrice+'</span></div><span class="sidebar-stock-chg '+cls+'">'+chg+'</span></div>';}).join('');container.querySelectorAll('.sidebar-stock-item').forEach(item=>{item.addEventListener('click',()=>selectSymbol(item.dataset.symbol));});}
function renderDashboardCards(){const container=document.getElementById('dashboardCards');if(!container)return;container.innerHTML=watchlist.map(symbol=>{const d=stockData[symbol];const isIN=symbol.endsWith('.NS');const curr=isIN?'₹':'$';const displaySym=symbol.replace('.NS','').replace('.BO','');if(!d)return '<div class="dash-card" data-symbol="'+symbol+'"><div class="dash-card-sym">'+displaySym+'</div><div class="dash-card-name">Loading...</div><div class="dash-card-price">—</div></div>';const cls=d.changePct>=0?'up':'down';const arrow=d.changePct>=0?'▲':'▼';const vol=d.volume>=1e6?(d.volume/1e6).toFixed(1)+'M':d.volume>=1e3?(d.volume/1e3).toFixed(0)+'K':String(d.volume);return '<div class="dash-card '+(selectedSymbol===symbol?'active':'')+' " data-symbol="'+symbol+'"><div class="dash-card-sym">'+displaySym+'</div><div class="dash-card-name">'+(d.name||symbol)+'</div><div class="dash-card-price">'+curr+d.price.toFixed(2)+'</div><div class="dash-card-chg '+cls+'">'+arrow+' '+Math.abs(d.changePct).toFixed(2)+'%</div><div class="dash-card-vol">Vol: '+vol+'</div></div>';}).join('');container.querySelectorAll('.dash-card').forEach(card=>{card.addEventListener('click',()=>selectSymbol(card.dataset.symbol));});}
function renderWatchlistGrid(){const container=document.getElementById('watchlistGrid');if(!container)return;if(watchlist.length===0){container.innerHTML='<p style="color:#94a3b8;font-size:.875rem">No stocks added. Use the search bar to add stocks.</p>';return;}container.innerHTML=watchlist.map(symbol=>{const d=stockData[symbol];const isIN=symbol.endsWith('.NS');const curr=isIN?'₹':'$';const displaySym=symbol.replace('.NS','').replace('.BO','');if(!d)return '<div class="wl-card" data-symbol="'+symbol+'"><div class="wl-card-top"><div><div class="wl-card-sym">'+displaySym+'</div><div class="wl-card-name">Loading...</div></div></div><div class="wl-card-price">—</div><button class="wl-remove-btn" data-symbol="'+symbol+'">✕</button></div>';const cls=d.changePct>=0?'up':'down';const arrow=d.changePct>=0?'▲':'▼';const trendPct=Math.min(Math.abs(d.changePct)*10,100);const trendColor=d.changePct>=0?'#22c55e':'#ef4444';const vol=d.volume>=1e6?(d.volume/1e6).toFixed(1)+'M':d.volume>=1e3?(d.volume/1e3).toFixed(0)+'K':String(d.volume);return '<div class="wl-card" data-symbol="'+symbol+'"><div class="wl-card-top"><div><div class="wl-card-sym">'+displaySym+'</div><div class="wl-card-name">'+(d.name||symbol)+'</div></div></div><div class="wl-card-price">'+curr+d.price.toFixed(2)+'</div><div class="wl-card-chg '+cls+'">'+arrow+' '+Math.abs(d.changePct).toFixed(2)+'% ('+curr+Math.abs(d.change).toFixed(2)+')</div><div class="wl-card-meta">Vol: '+vol+' · H: '+curr+(d.dayHigh?.toFixed(2)||'—')+' · L: '+curr+(d.dayLow?.toFixed(2)||'—')+'</div><div class="wl-card-trend"><div class="wl-card-trend-fill" style="width:'+trendPct+'%;background:'+trendColor+'"></div></div><button class="wl-remove-btn" data-symbol="'+symbol+'">✕</button></div>';}).join('');container.querySelectorAll('.wl-card').forEach(card=>{card.addEventListener('click',e=>{if(e.target.classList.contains('wl-remove-btn'))return;selectSymbol(card.dataset.symbol);navigateTo('dashboard');});});container.querySelectorAll('.wl-remove-btn').forEach(btn=>{btn.addEventListener('click',e=>{e.stopPropagation();removeSymbol(btn.dataset.symbol);});});}
async function fetchAndUpdateSymbol(symbol){const prev=stockData[symbol];const data=await fetchQuote(symbol);if(prev&&prev.price!==data.price)prevPrices[symbol]={price:prev.price,dir:data.price>prev.price?'up':'down'};stockData[symbol]=data;renderSidebarWatchlist();renderDashboardCards();renderWatchlistGrid();flashPriceCard(symbol,prevPrices[symbol]?.dir);const triggered=AlertManager.check(symbol,data.price);triggered.forEach(a=>{toast('🔔 '+symbol+' '+a.condition+' $'+a.price.toFixed(2)+' — now $'+data.price.toFixed(2),'warning',8000);AlertManager.render();});if(selectedSymbol===symbol)updateChartSubtitle(data);Suggester.render(stockData);}
function flashPriceCard(symbol,dir){if(!dir)return;const card=document.querySelector('.dash-card[data-symbol="'+symbol+'"] .dash-card-price');if(!card)return;card.classList.remove('flash-up','flash-down');void card.offsetWidth;card.classList.add(dir==='up'?'flash-up':'flash-down');setTimeout(()=>card.classList.remove('flash-up','flash-down'),800);}
async function refreshAll(){await Promise.allSettled(watchlist.map(s=>fetchAndUpdateSymbol(s)));}
function selectSymbol(symbol){selectedSymbol=symbol;renderSidebarWatchlist();renderDashboardCards();loadChart(symbol,selectedRange);}
async function loadChart(symbol,range){const loadingFor=symbol;document.getElementById('chartTitle').textContent=symbol.replace('.NS','').replace('.BO','');document.getElementById('chartSubtitle').textContent='';document.getElementById('chartPlaceholder').classList.add('hidden');const badge=document.getElementById('growthBadge');if(badge&&range!=='10y')badge.style.display='none';const key=symbol+'_'+range;const renderFn=rows=>{if(range==='10y')ChartManager.renderGrowth(symbol,rows,ChartManager.getType());else ChartManager.render(symbol,rows,ChartManager.getType());};if(historyCache[key]){renderFn(historyCache[key].data);const d=stockData[symbol];if(d)updateChartSubtitle(d);if((Date.now()-historyCache[key].ts)>=HISTORY_TTL){fetchHistory(symbol,range).then(rows=>{if(selectedSymbol!==loadingFor)return;renderFn(rows);const d2=stockData[symbol];if(d2)updateChartSubtitle(d2);});}return;}document.getElementById('chartSubtitle').textContent='Loading...';const rows=await fetchHistory(symbol,range);if(selectedSymbol!==loadingFor)return;renderFn(rows);const d=stockData[symbol];if(d)updateChartSubtitle(d);else document.getElementById('chartSubtitle').textContent='';}
function updateChartSubtitle(d){const el=document.getElementById('chartSubtitle');const isIN=d.symbol?.endsWith('.NS');const curr=isIN?'₹':'$';const cls=d.changePct>=0?'up':'down';const arrow=d.changePct>=0?'▲':'▼';const mockBadge=d.isMock?' <span style="font-size:.7rem;background:#fef3c7;color:#92400e;padding:1px 6px;border-radius:4px;font-weight:700">DEMO</span>':'';el.innerHTML='<span style="font-size:1rem;font-weight:700">'+curr+d.price.toFixed(2)+'</span> <span class="'+cls+'" style="margin-left:6px">'+arrow+' '+(d.change>=0?'+':'')+curr+Math.abs(d.change).toFixed(2)+' ('+d.changePct.toFixed(2)+'%)</span>'+mockBadge;}
function initSearch(){const input=document.getElementById('searchInput');const dropdown=document.getElementById('searchDropdown');if(!input)return;input.addEventListener('input',()=>{const q=input.value.trim().toUpperCase();if(!q){dropdown.classList.remove('open');return;}const matches=POPULAR_SYMBOLS.filter(s=>s.symbol.startsWith(q)||s.name.toUpperCase().includes(q)).slice(0,8);dropdown.innerHTML=matches.length?matches.map(s=>'<div class="search-item" data-symbol="'+s.symbol+'"><span class="sym">'+s.symbol+'</span><span class="name">'+s.name+'</span></div>').join(''):'<div class="search-item" data-symbol="'+q+'"><span class="sym">'+q+'</span><span class="name">Add to watchlist</span></div>';dropdown.classList.add('open');dropdown.querySelectorAll('.search-item[data-symbol]').forEach(item=>{item.addEventListener('click',()=>{addSymbol(item.dataset.symbol);input.value='';dropdown.classList.remove('open');});});});input.addEventListener('keydown',e=>{if(e.key==='Enter'){const q=input.value.trim();if(q){addSymbol(q);input.value='';dropdown.classList.remove('open');}}if(e.key==='Escape')dropdown.classList.remove('open');});document.addEventListener('click',e=>{if(!e.target.closest('.search-wrapper'))dropdown.classList.remove('open');});}
function initChartControls(){document.querySelectorAll('.chart-btn').forEach(btn=>{btn.addEventListener('click',()=>{document.querySelectorAll('.chart-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const type=btn.dataset.type;ChartManager.setType(type);if(!selectedSymbol)return;const cached=historyCache[selectedSymbol+'_'+selectedRange];if(cached){if(selectedRange==='10y')ChartManager.renderGrowth(selectedSymbol,cached.data,type);else ChartManager.render(selectedSymbol,cached.data,type);}else loadChart(selectedSymbol,selectedRange);});});document.querySelectorAll('.range-btn').forEach(btn=>{btn.addEventListener('click',()=>{document.querySelectorAll('.range-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');selectedRange=btn.dataset.range;if(selectedSymbol)loadChart(selectedSymbol,selectedRange);});});}
function initAddForm(){const form=document.getElementById('addSymbolForm');const input=document.getElementById('symbolInput');document.getElementById('addSymbolBtn')?.addEventListener('click',()=>{form.classList.remove('hidden');input.focus();});document.getElementById('cancelAdd')?.addEventListener('click',()=>{form.classList.add('hidden');input.value='';});document.getElementById('confirmAdd')?.addEventListener('click',()=>{if(input.value.trim()){addSymbol(input.value);input.value='';form.classList.add('hidden');}});input?.addEventListener('keydown',e=>{if(e.key==='Enter'&&input.value.trim()){addSymbol(input.value);input.value='';form.classList.add('hidden');}if(e.key==='Escape'){form.classList.add('hidden');input.value='';}});}
function populateForecastSelect(){const sel=document.getElementById('forecastSymbolSelect');if(!sel||sel.options.length>1)return;POPULAR_SYMBOLS.forEach(s=>{const opt=document.createElement('option');opt.value=s.symbol;opt.textContent=s.symbol+' — '+s.name;sel.appendChild(opt);});if(selectedSymbol)sel.value=selectedSymbol;}
function startRefresh(){let initialDone=false;Promise.allSettled(watchlist.map(s=>fetchAndUpdateSymbol(s))).then(()=>{if(!initialDone&&watchlist.length>0){initialDone=true;selectSymbol(watchlist[0]);}});refreshCountdown=REFRESH_MS/1000;setInterval(()=>{refreshCountdown--;const badge=document.getElementById('refreshBadge');if(badge)badge.textContent='● LIVE '+refreshCountdown+'s';if(refreshCountdown<=0){refreshCountdown=REFRESH_MS/1000;Object.keys(historyCache).forEach(k=>{historyCache[k].ts=0;});refreshAll();}},1000);}
function init(){
  initTheme();
  document.getElementById("themeToggle")?.addEventListener("click", toggleTheme);
  document.querySelectorAll('.nav-item').forEach(item=>{item.addEventListener('click',e=>{e.preventDefault();navigateTo(item.dataset.page);});});
  document.getElementById('alertsBtn')?.addEventListener('click',()=>document.getElementById('alertsPanel').classList.toggle('open'));
  document.getElementById('closeAlerts')?.addEventListener('click',()=>document.getElementById('alertsPanel').classList.remove('open'));
  document.getElementById('addAlertBtnPanel')?.addEventListener('click',()=>{const symbol=document.getElementById('alertSymbolPanel').value;const condition=document.getElementById('alertConditionPanel').value;const price=document.getElementById('alertPricePanel').value;if(!symbol){toast('Select a symbol','warning');return;}if(!price||isNaN(price)||parseFloat(price)<=0){toast('Enter a valid price','warning');return;}AlertManager.add(symbol,condition,price);AlertManager.render();document.getElementById('alertPricePanel').value='';toast('Alert set for '+symbol,'success');});
  document.getElementById('addAlertBtn')?.addEventListener('click',()=>{const symbol=document.getElementById('alertSymbol').value;const condition=document.getElementById('alertCondition').value;const price=document.getElementById('alertPrice').value;if(!symbol){toast('Select a symbol','warning');return;}if(!price||isNaN(price)||parseFloat(price)<=0){toast('Enter a valid price','warning');return;}AlertManager.add(symbol,condition,price);AlertManager.render();document.getElementById('alertPrice').value='';toast('Alert set for '+symbol,'success');});
  document.getElementById('forecastRunBtn')?.addEventListener('click',()=>{const sym=document.getElementById('forecastSymbolSelect').value;const range=document.querySelector('.fc-range-btn.active')?.dataset.fcrange||'1y';if(sym)ForecastPage.run(sym,range);});
  document.querySelectorAll('.fc-range-btn').forEach(btn=>{btn.addEventListener('click',()=>{document.querySelectorAll('.fc-range-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');});});
  initSearch();
  initChartControls();
  initAddForm();
  InvestmentIdeas.init();
  StockScanner.init();
  AlertManager.updateSymbolSelect(watchlist);
  AlertManager.render();
  renderSidebarWatchlist();
  renderDashboardCards();
  startRefresh();
}
document.addEventListener('DOMContentLoaded', init);
function initTheme(){const saved=localStorage.getItem("theme")||"light";document.documentElement.setAttribute("data-theme",saved);const btn=document.getElementById("themeToggle");if(btn)btn.textContent=saved==="dark"?"☀️":"🌙";}
function toggleTheme(){const current=document.documentElement.getAttribute("data-theme")||"light";const next=current==="dark"?"light":"dark";document.documentElement.setAttribute("data-theme",next);localStorage.setItem("theme",next);const btn=document.getElementById("themeToggle");if(btn)btn.textContent=next==="dark"?"☀️":"🌙";if(selectedSymbol&&historyCache[selectedSymbol+"_"+selectedRange]){const rows=historyCache[selectedSymbol+"_"+selectedRange].data;if(selectedRange==="10y")ChartManager.renderGrowth(selectedSymbol,rows,ChartManager.getType());else ChartManager.render(selectedSymbol,rows,ChartManager.getType());}}
